language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t rcollier1972/react-test -f ./client/Dockerfile.dev ./client
script:
        - docker run -e CI=true rcollier1972/react-test npm test

after_success:
        - docker build -t rcollier1972/multi-client ./client
        - docker build -t rcollier1972/multi-nginx ./nginx
        - docker build -t rcollier1972/multi-server ./server
        - docker build -t rcollier1972/multi-worker ./worker
        # Login to docker CLI
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
        #  Take those images and push them to docker hub
        - docker push rcollier1972/multi-client
        - docker push rcollier1972/multi-nginx
        - docker push rcollier1972/multi-server
        - docker push rcollier1972/multi-worker
deploy:
        provider: elasticbeanstalk
        region: "us-east-2"
#DockerReact-env.eba-9nppd8tc.us-east-2.elasticbeanstalk.com
        app: "multi-docker"
        env: "MultiDocker-env"
        bucket_name: "elasticbeanstalk-us-east-2-725421609531"
        bucket_path: "docker-multi"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY

